# (C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: Lint Code Base

on:
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7
        env:
          # true for entire repo, false for only new/modified files
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
