# (C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: Lint Code Base

on:
  pull_request:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter/slim@454ba4482ce2cd0c505bc592e83c06e1e37ade61
        env:
          # true for entire repo, false for only new/modified files
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
