# (C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: Secrets Scanner

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: hpe-actions/secrets-scanner/.github/workflows/secrets-scanner.yml@v2
